<?php
/**
 *
 */

use Drupal\Core\Entity\Sql\DefaultTableMapping;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\views\ViewsData;

/**
 * @see hook_entity_base_field_info()
 * @param \Drupal\Core\Entity\EntityTypeInterface $entity_type
 */
function entity_property_entity_base_field_info(\Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  $config = \Drupal::config("entity_property.properties." . $entity_type->id());
  if ($properties = $config->getRawData()) {
    foreach ($properties as $id => $property) {
      /** @var FieldDefinitionInterface[] $fields */
      $fields[$id] = \Drupal::service('entity_property')->buildFieldDefinition($id, $entity_type->id(), $property);
    }
    return $fields;
  }
}

/**
 * @see hook_entity_base_field_info_alter()
 * @param \Drupal\Core\Entity\EntityTypeInterface $entity_type
 */
function entity_property_entity_base_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  // Alter the mymodule_text field to use a custom class.
  if (!empty($fields['uid'])) {
    $fields['uid']->setDisplayOptions('form', ['region' => 'hidden']);
  }
  if (!empty($fields['created'])) {
    $fields['created']->setDisplayOptions('form', ['region' => 'hidden']);
  }
}

/**
 * @see hook_views_data_alter()
 */
function entity_property_views_data_alter(array &$data) {
  foreach ($data as $table_name => $table_info) {
    if (!empty($table_info['table']['entity type'])) {
      $entity_type_id = $table_info['table']['entity type'];
      /** @var BaseFieldDefinition[] $entity_field */
      $entity_field = \Drupal::service('entity_field.manager')->getFieldStorageDefinitions($entity_type_id);
      /** @var FieldDefinitionInterface  $field */
      foreach($entity_field as $field_name => $field) {
        if ($field->getType() === 'entity_reference' && $field->getProvider() === 'entity_property') {
          if (!empty($data[$table_name][$field_name]) && $data[$table_name][$field_name]['filter']['id'] === 'numeric') {
            $data[$table_name][$field_name]['filter']['id'] = "entity_property_list_field";
          }
        }
      }
    }
  }
}
